# Generated by Django 5.2.5 on 2025-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='freelancerlogin',
            name='fimage',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_images/'),
        ),
    ]
