# Generated by Django 5.2.5 on 2025-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0002_images_freelancerlogin_fimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogin',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
