# Generated by Django 5.2.5 on 2025-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0003_clientlogin_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogin',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='client_IDs/'),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freelancerlogin',
            name='fimage',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_IDs/'),
        ),
        migrations.AlterField(
            model_name='freelancerlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
