# Generated by Django 5.2.5 on 2025-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0004_alter_clientlogin_cimage_alter_clientlogin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerlogin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
