# Generated by Django 5.2.5 on 2025-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0006_freelancerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerinfo',
            old_name='user',
            new_name='freelancer',
        ),
        migrations.RenameField(
            model_name='freelancerinfo',
            old_name='languages',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='freelancerinfo',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerinfo',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
