# Generated by Django 5.2.5 on 2025-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0008_clientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
