# Generated by Django 5.2.5 on 2025-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0009_freelancerinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
