# Generated by Django 5.2.5 on 2025-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0010_clientinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
