# Generated by Django 5.2.5 on 2025-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0011_clientinfo_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
