# Generated by Django 5.2.5 on 2025-08-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0012_freelancerinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
