# Generated by Django 5.2.5 on 2025-08-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0013_freelancerinfo_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pay_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tech_stack', models.CharField(max_length=300)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillConnected.clientlogin')),
            ],
        ),
    ]
