# Generated by Django 5.2.5 on 2025-09-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0014_postedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillConnected.freelancerlogin')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillConnected.postedjobs')),
            ],
            options={
                'unique_together': {('freelancer', 'job')},
            },
        ),
    ]
