# Generated by Django 5.2.5 on 2025-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0015_appliedjobs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=20),
        ),
    ]
