# Generated by Django 5.2.5 on 2025-09-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0016_alter_appliedjobs_unique_together_appliedjobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
