# Generated by Django 5.2.5 on 2025-09-03 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0017_postedjobs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20)),
                ('receiver_id', models.IntegerField()),
                ('receiver_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
