# Generated by Django 5.2.5 on 2025-09-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0018_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
    ]
