# Generated by Django 5.2.5 on 2025-09-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0019_alter_chat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_profile_pic', models.ImageField(blank=True, null=True, upload_to='feedback_client_pics/')),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Design', 'Design'), ('Other', 'Other')], max_length=50)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillConnected.clientlogin')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SkillConnected.freelancerlogin')),
            ],
        ),
    ]
