# Generated by Django 5.2.5 on 2025-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
