# Generated by Django 5.2.6 on 2025-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0022_postedjobs_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedjobs',
            name='is_active',
        ),
        migrations.AddField(
            model_name='postedjobs',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
