# Generated by Django 5.2.6 on 2025-09-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0023_remove_postedjobs_is_active_postedjobs_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Verified', 'Verified'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=20),
        ),
    ]
