# Generated by Django 5.2.6 on 2025-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0025_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='company_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientlogin',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientlogin',
            name='company_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
