# Generated by Django 5.2.6 on 2025-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnected', '0026_clientinfo_company_url_clientlogin_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
