# Generated by Django 5.2.1 on 2025-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
