# Generated by Django 5.2.5 on 2025-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnect', '0002_clientlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogin',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='cimage/'),
        ),
        migrations.AddField(
            model_name='freelancerlogin',
            name='fimage',
            field=models.ImageField(blank=True, null=True, upload_to='fimage/'),
        ),
    ]
