# Generated by Django 5.2.5 on 2025-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillConnect', '0003_clientlogin_cimage_freelancerlogin_fimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
